// Vehicles Actions
export const GET_VEHICLES_INFO = 'GET_VEHICLE_INFO';
export const GET_VEHICLES_INFO_SUCCESS = 'GET_VEHICLE_INFO_SUCCESS';
export const GET_VEHICLES_INFO_FAILURE = 'GET_VEHICLE_INFO_FAILURE';

// Customers Actions
export const GET_CUSTOMERS_INFO = 'GET_CUSTOMERS_INFO';
export const GET_CUSTOMERS_INFO_SUCCESS = 'GET_CUSTOMERS_INFO_SUCCESS';
export const GET_CUSTOMERS_INFO_FAILURE = 'GET_CUSTOMERS_INFO_FAILURE';